#set text(font: "Times New Roman")
#set heading(numbering: "1.")

= Long-range phase coherence and tunable second order $phi_0$-Josephson effect in a Dirac semimetal $"1T-PtTe"_2$

*Pranava K. Sivakumar, Mostafa T. Ahari, Jae-Keun Kim, Yufeng Wu, Anvesh Dixit, George J. de Coster, Avanindra K. Pandeya, Matthew J. Gilbert, Stuart S. P. Parkin*

== Abstract
Superconducting diode effects have recently attracted much attention for their potential applications in superconducting logic circuits. Several pathways have been proposed to give rise to non-reciprocal critical currents in various superconductors and Josephson junctions. In this work, we establish the presence of a large Josephson diode effect in a type-II Dirac semimetal $"1T-PtTe"_2$ facilitated by its helical spin-momentum locking and distinguish it from extrinsic geometric effects. The magnitude of the Josephson diode effect is shown to be directly correlated to the large second-harmonic component of the supercurrent. We denote such junctions, where the relative phase between the two harmonics can be tuned by a magnetic field, as ‘tunable second order $phi_0$-junctions’. The direct correspondence between the second harmonic supercurrents and the diode effect in $"1T-PtTe"_2$ junctions at relatively low magnetic fields makes it an ideal platform to study the Josephson diode effect and Cooper quartet transport in Josephson junctions.

== Introduction
Non-reciprocal electrical transport in materials with broken inversion symmetry manifests itself as non-linear responses in electrical conductivity when time-reversal symmetry is also broken.#super[1] These responses are usually quantified through what is known as the magnetochiral anisotropy (MCA).#super[2,3,4] It was observed that the MCA was strongly enhanced in the superconducting state of non-centrosymmetric systems, promoting the search for non-reciprocal effects in superconducting systems.#super[5,6,7] Non-reciprocal critical currents titled the superconducting diode effect was first observed along with large MCA in a non-centrosymmetric thin film superlattice of superconductors.#super[8] Since its discovery, over the past few years, there has been a lot of interest in creating and understanding superconducting and Josephson diodes composed of various materials, from both a fundamental and technological perspective.#super[8,9,10,11,12,13,14,15,16,17] These devices exhibit non-reciprocal superconducting critical currents and allow for unidirectional propagation of supercurrents and normal currents in the opposite direction, which is quite promising for the creation of various low dissipative technologies. The observation of a supercurrent diode effect requires the breaking of both inversion and time-reversal symmetries (TRS),#super[18] which also makes it a useful ‘tool’ providing insights into a material’s broken symmetries and other properties in the superconducting state such as the nature of spin-orbit coupling#super[14] and in the determination of a chiral superconducting state that breaks time-reversal symmetry.#super[19] There have been multiple pathways proposed for the creation of the supercurrent diode effect, where most of them rely on the creation of Cooper pairs with non-zero momentum either due to the presence of spin-momentum locking in the material or Meissner screening currents induced by the magnetic field.#super[13,17,20,21,22,23,24] However, experimentally disentangling these two effects has been challenging.

In this paper, we perform a detailed study of the Josephson diode effect (JDE or $Delta I_c$) in a transition metal dichalcogenide and Dirac semimetal system ($"1T-PtTe"_2$) in different current and magnetic field geometries. This allows for distinguishing between intrinsic contributions to the JDE arising from the band structure and extrinsic junction geometric effects and establish the presence of helical spin-momentum locking in the system. The supercurrent behavior in the junction is studied in detail by considering a current-phase relationship (CPR) with a second harmonic term that we refer to as a ‘tunable second order $phi_0$-junction’ CPR. The observations from this CPR are verified by measuring the evolution of critical currents in $"PtTe"_2$ junctions in the presence of a magnetic flux and a magnetic field that is needed to induce the JDE. These measurements are used to provide direct evidence that the oscillations in $Delta I_c$ are second harmonic in nature with nodes occurring at every half-magnetic flux quantum $(Phi_0 / 2)$ and that the magnitude of $Delta I_c$ is closely related to the magnitude of second harmonic supercurrents in the system and a phase difference ($delta$) between the first and second harmonic components, as predicted from the CPR. This CPR combined with the tunability of $delta$ with a magnetic field provides the possibility of controlling the relative magnitudes and direction of first- and second-harmonic supercurrents leading to controllable flow of Cooper pairs and Cooper quartets. Based on the transparency of the junctions studied, we also comment on the potential contribution of Meissner screening currents to the observed JDE, as compared to the helical spin-momentum locking in $"PtTe"_2$. Finally, the role of the helical spin-momentum locked topological states in the formation of high transparency interfaces and phase coherent higher order Andreev reflections in $"PtTe"_2$ junctions that leads to the presence of a strong second harmonic term and hence a large JDE in the system is discussed.

== Results
=== Lateral Josephson junctions of $"PtTe"_2$
The Josephson junctions in this study are fabricated from mechanically exfoliated flakes of $"1T-PtTe"_2$ (see Methods section for details on crystal growth and device fabrication). @fig-1 shows a schematic of the device geometry used in this study. The junctions are formed by creating a narrow constriction in a $"PtTe"_2$ flake using electron beam lithography and reactive ion etching. The width of the constriction is varied from 200 to 500 nm, while the length is kept constant at 100 nm. The superconducting contacts are made of NbTi, which has a critical temperature of ~9 K. The junctions are measured in a dilution refrigerator with a base temperature of 10 mK.

#figure(
  align(center, [(Figure 1 placeholder)]),
  caption: [
    *Fig. 1* Device characteristics and Josephson diode effect. *a* Schematic of the $"PtTe"_2$ Josephson junction device. The junction is formed by a narrow constriction in a $"PtTe"_2$ flake, contacted by NbTi superconducting electrodes. The in-plane magnetic field $B_("//")$ is applied parallel to the current direction, and the out-of-plane magnetic field $B_bot$ is applied perpendicular to the junction plane. *b* Optical micrograph of a typical device. Scale bar, 5 µm. *c* Atomic force microscopy (AFM) image of the junction area. Scale bar, 500 nm. *d* Current-voltage ($I-V$) characteristics of the junction at $T = 10$ mK, showing a clear supercurrent branch and hysteretic behavior. The switching current $I_("sw")$ and retrapping current $I_r$ are indicated. *e* Color plot of the differential resistance $d V / d I$ as a function of bias current $I$ and in-plane magnetic field $B_("//")$. The critical current $I_c$ shows a strong dependence on $B_("//")$, exhibiting a pronounced Josephson diode effect. *f* Diode efficiency $eta$ as a function of $B_("//")$. The efficiency reaches a maximum of ~35% at $B_("//") approx 150$ mT.
  ]
) <fig-1>

=== Josephson diode effect
The Josephson diode effect is characterized by a non-reciprocal critical current, i.e., $I_c^+ != I_c^-$, where $I_c^+$ and $I_c^-$ are the critical currents for positive and negative current bias, respectively. This effect is quantified by the diode efficiency $eta = (I_c^+ - I_c^-) / (I_c^+ + I_c^-)$. @fig-1 shows the differential resistance $d V / d I$ as a function of bias current $I$ and in-plane magnetic field $B_("//")$. The critical current $I_c$ is clearly asymmetric with respect to the sign of $B_("//")$. The diode efficiency $eta$ is plotted as a function of $B_("//")$ in @fig-1. The efficiency is zero at zero field, increases with $B_("//")$, reaches a maximum of ~35% at $B_("//") approx 150$ mT, and then decreases. This large and tunable Josephson diode effect is the main finding of this work.

=== Fraunhofer pattern and current-phase relationship
To understand the origin of the Josephson diode effect, we measured the Fraunhofer pattern, i.e., the critical current $I_c$ as a function of the out-of-plane magnetic field $B_bot$, for different values of the in-plane magnetic field $B_("//")$. The results are shown in @fig-2.

#figure(
  align(center, [(Figure 2 placeholder)]),
  caption: [
    *Fig. 2* Fraunhofer patterns and current-phase relationship. *a-c* Fraunhofer patterns for $B_("//") = 0$, 75, and 150 mT, respectively. The black dots are experimental data, and the red curves are fits to the data using the model described in the text. *d-f* Reconstructed current-phase relationships (CPRs) corresponding to the Fraunhofer patterns in *a-c*. The CPRs are skewed and show a significant second harmonic component, which is responsible for the Josephson diode effect.
  ]
) <fig-2>

At $B_("//") = 0$, the Fraunhofer pattern is symmetric and resembles the standard Fraunhofer pattern of a short and wide junction, indicating a uniform current distribution. As $B_("//")$ increases, the pattern becomes asymmetric, and the central peak shifts away from zero $B_bot$. This asymmetry is a hallmark of a skewed current-phase relationship (CPR). We model the CPR as $I(phi) = I_1 sin(phi) + I_2 sin(2 phi + delta)$, where $I_1$ and $I_2$ are the amplitudes of the first and second harmonics, and $delta$ is a phase shift. The Fraunhofer pattern is the Fourier transform of the CPR. By fitting the experimental Fraunhofer patterns, we can extract the CPR parameters. The reconstructed CPRs are shown in @fig-2. The CPRs are clearly skewed and exhibit a significant second harmonic component, which grows with $B_("//")$. The presence of the second harmonic is responsible for the Josephson diode effect.

=== Temperature dependence of the Josephson diode effect
We also studied the temperature dependence of the Josephson diode effect. @fig-3 shows the diode efficiency $eta$ as a function of temperature for different values of $B_("//")$. The diode effect is robust and persists up to the critical temperature of the junction. The efficiency decreases with increasing temperature, which is consistent with the thermal smearing of the Andreev bound states.

#figure(
  align(center, [(Figure 3 placeholder)]),
  caption: [
    *Fig. 3* Temperature dependence of the Josephson diode effect. Diode efficiency $eta$ as a function of temperature for different in-plane magnetic fields. The diode effect persists up to the critical temperature of the junction.
  ]
) <fig-3>

== Discussion
Our results provide clear evidence for a large and tunable Josephson diode effect in $"1T-PtTe"_2$ junctions. The effect is attributed to the presence of a strong second harmonic in the CPR, which is induced by the in-plane magnetic field. The helical spin-momentum locking of the surface states in the Dirac semimetal $"1T-PtTe"_2$ is likely responsible for the unconventional CPR. The in-plane magnetic field breaks time-reversal symmetry and lifts the spin degeneracy, leading to a phase shift in the CPR and a non-reciprocal critical current.

The ability to tune the diode effect with a magnetic field opens up possibilities for applications in superconducting electronics, such as rectifiers, switches, and logic circuits. The large diode efficiency observed in our devices is promising for practical applications. Furthermore, the study of the Josephson effect in topological materials provides a powerful tool to probe their exotic electronic properties.